version: "3.7"

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgis
    image: postgis:qm
    ports:
      - "55432:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - "./db/postgresql-data:/var/lib/postgresql/data"
